name: Deploy FastAPI Backend

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Zip Backend
        run: |
          zip -r release.zip backend

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: Jobpulse-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip