name: JobPulse Scheduler

on:
  schedule:
    - cron: "* * * * *"

  workflow_dispatch:

jobs:
  trigger-job-check:

    runs-on: ubuntu-latest

    steps:

      - name: Trigger backend scheduler endpoint

        run: |
          curl --fail --silent --show-error \
          "https://jobpulse-hghkebgcafc5erda.eastus-01.azurewebsites.net/run-scheduler"